### ISSUE TITLE
Adjust the design of the invoices page

### ISSUE THREAD

**Issue by GabrielAdward** [AlexTelon/FlexiCharge-My-pages#181]
Describe the solution you'd like

Adjust the following:

- [ ] Change the current table design to the one used on the charging history page
- [ ]  Place the table on a card
- [ ]  Change the color of the element containing the title for each column to #222222
- [ ]  The title for each column should be changed to #76BD76
- [ ]  There should be a black line Between each row
- [ ]  The text in each row should also be black
- [ ] The "view invoice" button should have the #76BD76 color and the text should have the white color

Additional context
https://github.com/AlexTelon/FlexiCharge-Admin-GUI/blob/documentation/documentation/design-guideline.md
